import type { SolarService } from '../types';

export const MOCK_SERVICES: SolarService[] = [
	 {ID: 1, ModelName: "Аккумулятор Vektor GL 12-100", Price: 10000.0, Type: "battery", Power: 0, Capacity: 100, Description: "Аккумуляторные батареи VEKTOR ENERGY серии GEL (GL) изготовлены по технологии AGM+GEL. Электролит увязан в гель посредством оксида кремния SiO2. Имеют отличные разрядные и эксплуатационные характеристики.", ImageKey: "AKB100.jpg", VideoKey: "solar.webm", Status: "active", IsDeleted: false},
	 {ID: 2, ModelName: "Аккумулятор Vektor GL 12-150", Price: 15000.0, Type: "battery", Power: 0, Capacity: 150, Description: "Аккумуляторные батареи VEKTOR ENERGY серии GEL (GL) изготовлены по технологии AGM+GEL. Электролит увязан в гель посредством оксида кремния SiO2. Имеют отличные разрядные и эксплуатационные характеристики.", ImageKey: "AKB150.jpg", VideoKey: "solar.webm", Status: "active", IsDeleted: false},
	 {ID: 3, ModelName: "Аккумулятор Vektor GL 12-200", Price: 20000.0, Type: "battery", Power: 0, Capacity: 200, Description: "Аккумуляторные батареи VEKTOR ENERGY серии GEL (GL) изготовлены по технологии AGM+GEL. Электролит увязан в гель посредством оксида кремния SiO2. Имеют отличные разрядные и эксплуатационные характеристики.", ImageKey: "AKB200.jpg", VideoKey: "solar.webm", Status: "active", IsDeleted: false},
	 {ID: 4, ModelName: "Солнечная панель DELTA_NXT500", Price: 12000.0, Type: "panel", Power: 500, Capacity: 0, Description: "Фотоэлектрический солнечный модуль (ФСМ) DELTA NXT 400-54/2 M10 HC DELTA NXT - это серия фотоэлектрических модулей, выполненных из материалов экстра-класса. При невысокой интенсивности солнечного излучения, DELTA NXT вырабатывают больше электроэнергии, чем стандартные солнечные модули с аналогичными характеристиками.", ImageKey: "DELTA_NXT500.jpg", VideoKey: "solar1.webm", Status: "active", IsDeleted: false},
	 {ID: 5, ModelName: "Солнечная панель GWS280", Price: 89000.0, Type: "panel", Power: 200, Capacity: 0, Description: "При производстве солнечных панелей GWS используются высококачественные материалы, что гарантирует наивысшее качество изделий: прочный защитный слой специального закалённого стекла и усиленная рамка из анодированного алюминия, устойчивая к коррозии, обеспечивает высокий класс защиты от механических повреждений, влаги и высокое сопротивление экстремальной ветровой нагрузке.", ImageKey: "GWS280.jpg", VideoKey: "solar1.webm", Status: "active", IsDeleted: false},
	 {ID: 6, ModelName: "Солнечная панель M300WT", Price: 26000.0, Type: "panel", Power: 300, Capacity: 0, Description: "Солнечные батареи серии М300 являются фотоэлектрическими модулями, выполненными из материалов экстра-класса. При невысокой интенсивности солнечного излучения, вырабатывают больше электроэнергии, чем стандартные солнечные модули с аналогичными характеристиками.", ImageKey: "M300WT.jpg", VideoKey: "solar1.webm", Status: "active", IsDeleted: false},
	];

export const DEFAULT_IMAGE = "https://unsplash.com";